name: Test
on: 
    workflow_dispatch:
    push:
        branches:
            - main
jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
        - name: get code
          uses: actions/checkout@v3
        - name: Cache
          uses: actions/cache@v3
          with:
            key: node-key-${{ hashFiles('**/package-lock.json') }}
            path: ~/.npm
        - name: dependencies
          run: npm ci
        - name: Start
          run: npm start
    report:
        if: failure()
        needs: testing
        runs-on: ubuntu-latest
        steps:
        - name: Something Wrong
          run: Opps something went wrong

        